POST http://localhost:3000/pessoas
Content-Type:  application/json

{
    "nome": "claudio",
    "idade": 20
}

###

GET http://localhost:3000/pessoas


### 

PUT http://localhost:3000/pessoas/5b915e09-0846-4f4b-abd7-6a1076e5a7c6
Content-Type:  application/json

{
    "nome": "Claudio silva",
    "idade": 21
}

###

DELETE http://localhost:3000/pessoas/e2d2539b-5113-4c46-9551-7d7f7cdee5d1

