POST https://modeloapinodefastify.onrender.com/pessoas
Content-Type:  application/json

{
    "nome": "claudio",
    "idade": 20
}

###

GET https://modeloapinodefastify.onrender.com/pessoas


### 

PUT https://modeloapinodefastify.onrender.com/pessoas/5b915e09-0846-4f4b-abd7-6a1076e5a7c6
Content-Type:  application/json

{
    "nome": "Claudio",
    "idade": 21
}

###

DELETE https://modeloapinodefastify.onrender.com/pessoas/e2d2539b-5113-4c46-9551-7d7f7cdee5d1

