POST https://modeloapinodefastify.onrender.com/pessoas
Content-Type:  application/json

{
    "nome": "Isabella",
    "idade": 18
}

###

GET https://modeloapinodefastify.onrender.com/pessoas


### 

PUT https://modeloapinodefastify.onrender.com/pessoas/5b915e09-0846-4f4b-abd7-6a1076e5a7c6
Content-Type:  application/json

{
    "nome": "Claudio",
    "idade": 21
}

###

DELETE https://modeloapinodefastify.onrender.com/pessoas/77652d46-c4dd-4350-9c42-1f54f268f80e

